name: freetogames_dio_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 4.0.6
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.6.0
  url_launcher: 6.1.7
  intl: 0.18.0
  flutter: 
    sdk: flutter
  carousel_slider: ^4.2.1
  filter_list: ^1.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - lib/app/assets/images/
  uses-material-design: true

